server:
  port: 80
#thymeleaf start
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

#开发时关闭缓存,不然没法看到实时页面
    cache: false
    #thymeleaf end
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
logging:
  level: debug
